<?php

namespace BackBundle\Repository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends \Doctrine\ORM\EntityRepository
{
    public function companyPaginationAPI($start = 0, $max = null)
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c')
            ->distinct('c.id')
            ->orderBy('c.id ', 'ASC');
        if ($max) {
            $preparedQuery = $qb->getQuery()
                ->setMaxResults($max)
                ->setFirstResult($start);
        } else {
            $preparedQuery = $qb->getQuery();
        }
        return $preparedQuery->getResult();
    }
}
