<?php

namespace BackBundle\Repository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends \Doctrine\ORM\EntityRepository
{
    public function customerPaginationAPI($search = null, $start = 0, $max = null)
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c')
            ->distinct('c.id');
        if ($search) {
            $qb->where('c.lastName like :search')
                ->orWhere('c.firstName like :search')
                ->setParameter('search', "%" . $search . "%");
        }
        $qb->orderBy('c.id ', 'ASC');

        if ($max) {
            $preparedQuery = $qb->getQuery()
                ->setMaxResults($max)
                ->setFirstResult($start);
        } else {
            $preparedQuery = $qb->getQuery();
        }
        return $preparedQuery->getResult();
    }
}
