<?php

namespace BackBundle\Repository;

/**
 * DesignApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DesignApplicationRepository extends \Doctrine\ORM\EntityRepository
{
}
