<?php

namespace BackBundle\Repository;

/**
 * GroupCustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupCustomerRepository extends \Doctrine\ORM\EntityRepository
{
}
